<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibraryManagement.Business\LibraryManagement.Business.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\Books\" />
    <Folder Include="ViewModels\BookCopies\" />
    <Folder Include="ViewModels\Loans\" />
    <Folder Include="Views\Book\" />
    <Folder Include="Views\BookCopies\" />
    <Folder Include="Views\Loan\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.0" />
  </ItemGroup>

</Project>
