// <auto-generated />
using System;
using LibraryManagement.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523122553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Models.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AuthorId")
                        .HasName("PK__Authors__70DAFC34CC5F8E3C");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BookId")
                        .HasName("PK__Books__3DE0C2070B8D05FB");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.HasIndex(new[] { "Title" }, "IX_Books_Title");

                    b.HasIndex(new[] { "ISBN" }, "UQ__Books__447D36EAF0D6485A")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookAuthor", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookCategory", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookCopy", b =>
                {
                    b.Property<Guid>("CopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateOnly>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Available");

                    b.HasKey("CopyId")
                        .HasName("PK__BookCopi__C26CCCC5205CE687");

                    b.HasIndex(new[] { "BookId" }, "IX_BookCopies_BookId");

                    b.HasIndex(new[] { "Status" }, "IX_BookCopies_Status");

                    b.HasIndex(new[] { "Barcode" }, "UQ__BookCopi__177800D33A29574E")
                        .IsUnique();

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0B3AD84380");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Categori__8517B2E0882B8F80")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Fine", b =>
                {
                    b.Property<Guid>("FineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("LoanDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Unpaid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FineId")
                        .HasName("PK__Fines__9D4A9B2CA6D51367");

                    b.HasIndex("LoanDetailId");

                    b.HasIndex(new[] { "UserId" }, "IX_Fines_UserId");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Loan", b =>
                {
                    b.Property<Guid>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("BorrowedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("BorrowerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProcessedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Borrowed");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LoanId")
                        .HasName("PK__Loans__4F5AD457CBAEC671");

                    b.HasIndex(new[] { "BorrowerUserId" }, "IX_Loans_BorrowerUserId");

                    b.HasIndex(new[] { "ProcessedByUserId" }, "IX_Loans_ProcessedByUserId");

                    b.HasIndex(new[] { "Status" }, "IX_Loans_Status");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.LoanDetail", b =>
                {
                    b.Property<Guid>("LoanDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CopyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Borrowed");

                    b.HasKey("LoanDetailId")
                        .HasName("PK__LoanDeta__760C10C83689AB7B");

                    b.HasIndex(new[] { "CopyId" }, "IX_LoanDetails_CopyId");

                    b.HasIndex(new[] { "LoanId" }, "IX_LoanDetails_LoanId");

                    b.HasIndex(new[] { "CopyId" }, "UX_LoanDetails_OneActiveLoanPerCopy")
                        .IsUnique()
                        .HasFilter("([Status]='Borrowed')");

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublisherId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PublisherId")
                        .HasName("PK__Publishe__4C657FABD9BFF99F");

                    b.HasIndex(new[] { "PublisherName" }, "UQ__Publishe__5F0E22495C071047")
                        .IsUnique();

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CopyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReservationId")
                        .HasName("PK__Reservat__B7EE5F24EE6920B8");

                    b.HasIndex(new[] { "BookId" }, "IX_Reservations_BookId");

                    b.HasIndex(new[] { "UserId" }, "IX_Reservations_UserId");

                    b.HasIndex(new[] { "CopyId" }, "UX_Reservations_OneActiveReservationPerCopy")
                        .IsUnique()
                        .HasFilter("([CopyId] IS NOT NULL AND ([Status] IN ('Pending', 'ReadyForPickup')))");

                    b.HasIndex(new[] { "UserId", "BookId" }, "UX_Reservations_OneActiveReservationPerMemberBook")
                        .IsUnique()
                        .HasFilter("([Status] IN ('Pending', 'ReadyForPickup'))");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasTrigger("TRG_Reservations_CopyMatchesBook");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1AC2BA1463");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B61606178B3F3")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CF1485FA5");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email");

                    b.HasIndex(new[] { "RoleId" }, "IX_Users_RoleId");

                    b.HasIndex(new[] { "Status" }, "IX_Users_Status");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534911F2EB8")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Book", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Author", null)
                        .WithMany("Books")
                        .HasForeignKey("AuthorId");

                    b.HasOne("LibraryManagement.Models.Models.Category", null)
                        .WithMany("Books")
                        .HasForeignKey("CategoryId");

                    b.HasOne("LibraryManagement.Models.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .HasConstraintName("FK_Books_Publishers");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookAuthor", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookCategory", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookCopy", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK_BookCopies_Books");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Fine", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.LoanDetail", "LoanDetail")
                        .WithMany("Fines")
                        .HasForeignKey("LoanDetailId")
                        .HasConstraintName("FK_Fines_LoanDetails");

                    b.HasOne("LibraryManagement.Models.Models.User", "User")
                        .WithMany("Fines")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Fines_Users");

                    b.Navigation("LoanDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Loan", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.User", "BorrowerUser")
                        .WithMany("LoanBorrowerUsers")
                        .HasForeignKey("BorrowerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Loans_BorrowerUser");

                    b.HasOne("LibraryManagement.Models.Models.User", "ProcessedByUser")
                        .WithMany("LoanProcessedByUsers")
                        .HasForeignKey("ProcessedByUserId")
                        .HasConstraintName("FK_Loans_ProcessedByUser");

                    b.Navigation("BorrowerUser");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.LoanDetail", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.BookCopy", "Copy")
                        .WithOne("LoanDetail")
                        .HasForeignKey("LibraryManagement.Models.Models.LoanDetail", "CopyId")
                        .IsRequired()
                        .HasConstraintName("FK_LoanDetails_BookCopies");

                    b.HasOne("LibraryManagement.Models.Models.Loan", "Loan")
                        .WithMany("LoanDetails")
                        .HasForeignKey("LoanId")
                        .IsRequired()
                        .HasConstraintName("FK_LoanDetails_Loans");

                    b.Navigation("Copy");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Reservation", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Books");

                    b.HasOne("LibraryManagement.Models.Models.BookCopy", "Copy")
                        .WithOne("Reservation")
                        .HasForeignKey("LibraryManagement.Models.Models.Reservation", "CopyId")
                        .HasConstraintName("FK_Reservations_BookCopies");

                    b.HasOne("LibraryManagement.Models.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Users");

                    b.Navigation("Book");

                    b.Navigation("Copy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.User", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookCategories");

                    b.Navigation("BookCopies");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookCopy", b =>
                {
                    b.Navigation("LoanDetail");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Category", b =>
                {
                    b.Navigation("BookCategories");

                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Loan", b =>
                {
                    b.Navigation("LoanDetails");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.LoanDetail", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.User", b =>
                {
                    b.Navigation("Fines");

                    b.Navigation("LoanBorrowerUsers");

                    b.Navigation("LoanProcessedByUsers");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
