// <auto-generated />
using System;
using LibraryManagement.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605025535_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Models.Models.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountId");

                    b.HasIndex(new[] { "Role" }, "IX_Accounts_Role");

                    b.HasIndex(new[] { "Email" }, "UQ_Accounts_Email")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AuthorId")
                        .HasName("PK__Authors__70DAFC34CC5F8E3C");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BookId")
                        .HasName("PK__Books__3DE0C2070B8D05FB");

                    b.HasIndex("PublisherId");

                    b.HasIndex(new[] { "Title" }, "IX_Books_Title");

                    b.HasIndex(new[] { "ISBN" }, "UQ__Books__447D36EAF0D6485A")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookAuthor", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookCategory", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookCopy", b =>
                {
                    b.Property<Guid>("CopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateOnly>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Available");

                    b.HasKey("CopyId")
                        .HasName("PK__BookCopi__C26CCCC5205CE687");

                    b.HasIndex(new[] { "BookId" }, "IX_BookCopies_BookId");

                    b.HasIndex(new[] { "Status" }, "IX_BookCopies_Status");

                    b.HasIndex(new[] { "Barcode" }, "UQ__BookCopi__177800D33A29574E")
                        .IsUnique();

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0B3AD84380");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Categori__8517B2E0882B8F80")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Fine", b =>
                {
                    b.Property<Guid>("FineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("LoanDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Unpaid");

                    b.HasKey("FineId")
                        .HasName("PK__Fines__9D4A9B2CA6D51367");

                    b.HasIndex("LoanDetailId");

                    b.HasIndex(new[] { "ReaderId" }, "IX_Fines_ReaderId");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Loan", b =>
                {
                    b.Property<Guid>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("BorrowedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("BorrowerReaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProcessedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Borrowed");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LoanId")
                        .HasName("PK__Loans__4F5AD457CBAEC671");

                    b.HasIndex(new[] { "BorrowerReaderId" }, "IX_Loans_BorrowerReaderId");

                    b.HasIndex(new[] { "ProcessedByAccountId" }, "IX_Loans_ProcessedByAccountId");

                    b.HasIndex(new[] { "Status" }, "IX_Loans_Status");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.LoanDetail", b =>
                {
                    b.Property<Guid>("LoanDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CopyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Borrowed");

                    b.HasKey("LoanDetailId")
                        .HasName("PK__LoanDeta__760C10C83689AB7B");

                    b.HasIndex(new[] { "CopyId" }, "IX_LoanDetails_CopyId");

                    b.HasIndex(new[] { "LoanId" }, "IX_LoanDetails_LoanId");

                    b.HasIndex(new[] { "CopyId" }, "UX_LoanDetails_OneActiveLoanPerCopy")
                        .IsUnique()
                        .HasFilter("([Status]='Borrowed')");

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublisherId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PublisherId")
                        .HasName("PK__Publishe__4C657FABD9BFF99F");

                    b.HasIndex(new[] { "PublisherName" }, "UQ__Publishe__5F0E22495C071047")
                        .IsUnique();

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Reader", b =>
                {
                    b.Property<Guid>("ReaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReaderId");

                    b.HasIndex(new[] { "Status" }, "IX_Readers_Status");

                    b.HasIndex(new[] { "Email" }, "UQ_Readers_Email")
                        .IsUnique();

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReservationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.HasKey("ReservationId");

                    b.HasIndex(new[] { "ReaderId" }, "IX_Reservations_ReaderId");

                    b.HasIndex(new[] { "RoomId" }, "IX_Reservations_RoomId");

                    b.HasIndex(new[] { "Status" }, "IX_Reservations_Status");

                    b.HasIndex(new[] { "ReaderId" }, "UQ_Reservations_OneActivePerReader")
                        .IsUnique()
                        .HasFilter("([Status] IN ('Pending', 'Confirmed'))");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Available");

                    b.HasKey("RoomId");

                    b.HasIndex(new[] { "Status" }, "IX_Rooms_Status");

                    b.HasIndex(new[] { "RoomName" }, "UQ_Rooms_RoomName")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.UserProfile", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("ReaderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserProfileId");

                    b.HasIndex(new[] { "AccountId" }, "UQ_UserProfiles_AccountId")
                        .IsUnique()
                        .HasFilter("[AccountId] IS NOT NULL");

                    b.HasIndex(new[] { "ReaderId" }, "UQ_UserProfiles_ReaderId")
                        .IsUnique()
                        .HasFilter("[ReaderId] IS NOT NULL");

                    b.ToTable("UserProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_UserProfiles_OneOwner", "([ReaderId] IS NOT NULL AND [AccountId] IS NULL) OR ([ReaderId] IS NULL AND [AccountId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Book", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .HasConstraintName("FK_Books_Publishers");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookAuthor", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookCategory", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookCopy", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK_BookCopies_Books");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Fine", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.LoanDetail", "LoanDetail")
                        .WithMany("Fines")
                        .HasForeignKey("LoanDetailId")
                        .HasConstraintName("FK_Fines_LoanDetails");

                    b.HasOne("LibraryManagement.Models.Models.Reader", "Reader")
                        .WithMany("Fines")
                        .HasForeignKey("ReaderId")
                        .IsRequired()
                        .HasConstraintName("FK_Fines_Readers");

                    b.Navigation("LoanDetail");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Loan", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Reader", "BorrowerReader")
                        .WithMany("Loans")
                        .HasForeignKey("BorrowerReaderId")
                        .IsRequired()
                        .HasConstraintName("FK_Loans_BorrowerReader");

                    b.HasOne("LibraryManagement.Models.Models.Account", "ProcessedByAccount")
                        .WithMany("ProcessedLoans")
                        .HasForeignKey("ProcessedByAccountId")
                        .HasConstraintName("FK_Loans_ProcessedByAccount");

                    b.Navigation("BorrowerReader");

                    b.Navigation("ProcessedByAccount");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.LoanDetail", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.BookCopy", "Copy")
                        .WithOne("LoanDetail")
                        .HasForeignKey("LibraryManagement.Models.Models.LoanDetail", "CopyId")
                        .IsRequired()
                        .HasConstraintName("FK_LoanDetails_BookCopies");

                    b.HasOne("LibraryManagement.Models.Models.Loan", "Loan")
                        .WithMany("LoanDetails")
                        .HasForeignKey("LoanId")
                        .IsRequired()
                        .HasConstraintName("FK_LoanDetails_Loans");

                    b.Navigation("Copy");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Reservation", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Reader", "Reader")
                        .WithMany("Reservations")
                        .HasForeignKey("ReaderId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Readers");

                    b.HasOne("LibraryManagement.Models.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Rooms");

                    b.Navigation("Reader");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.UserProfile", b =>
                {
                    b.HasOne("LibraryManagement.Models.Models.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("LibraryManagement.Models.Models.UserProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_UserProfiles_Accounts");

                    b.HasOne("LibraryManagement.Models.Models.Reader", "Reader")
                        .WithOne("Profile")
                        .HasForeignKey("LibraryManagement.Models.Models.UserProfile", "ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_UserProfiles_Readers");

                    b.Navigation("Account");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Account", b =>
                {
                    b.Navigation("ProcessedLoans");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookCategories");

                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.BookCopy", b =>
                {
                    b.Navigation("LoanDetail");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Category", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Loan", b =>
                {
                    b.Navigation("LoanDetails");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.LoanDetail", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Reader", b =>
                {
                    b.Navigation("Fines");

                    b.Navigation("Loans");

                    b.Navigation("Profile");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LibraryManagement.Models.Models.Room", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
