<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="AI\" />
    <Folder Include="DTOs\BookDTOs\" />
    <Folder Include="Helpers\" />
    <Folder Include="Validators\BookValidators\" />
  </ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="MailKit" Version="4.17.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.27" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.27">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.27" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.27">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MimeKit" Version="4.17.0" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\LibraryManagement.Data\LibraryManagement.Data.csproj" />
	  <ProjectReference Include="..\LibraryManagement.Models\LibraryManagement.Models.csproj" />
	</ItemGroup>

</Project>
